apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Java App Build 

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the build and deploy from

jobs:
  
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
      - name: Build Java App
        uses: docker://maven:3.9-eclipse-temurin-11
        run: |
          mvn clean package
